#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    GrassBlock = 2,
    Dirt = 3,
    Cobblestone = 4,
    OakPlanks = 5,
    Bedrock = 6,
    Water = 7,
    Sand = 8,
    Gravel = 9,
    GoldOre = 10,
    IronOre = 11,
    CoalOre = 12,
    OakLog = 13,
    OakLeaves = 14,
    Glass = 15,
    CraftingTable = 16,
    Furnace = 17,
    Chest = 18,
    Torch = 19,
    Snow = 20,
    Ice = 21,
    Glowstone = 22,
    Netherrack = 23,
    SoulSand = 24,
    Deepslate = 25,
    SnowBlock = 26,
    CoarseDirt = 27,
    Podzol = 28,
    DeepslateIronOre = 29,
    DeepslateCoalOre = 30,
    DeepslateGoldOre = 31,
    DeepslateRedstoneOre = 32,
    DeepslateDiamondOre = 33,
    DeepslateEmeraldOre = 34,
    DeepslateLapisOre = 35,
    DeepslateCopperOre = 36,
    DiamondBlock = 37,
    IronBlock = 38,
    GoldBlock = 39,
    EmeraldBlock = 40,
    LapisBlock = 41,
    RedstoneBlock = 42,
    Bricks = 43,
    Bookshelf = 44,
    MossyCobblestone = 45,
    Obsidian = 46,
    Spawner = 47,
    Sandstone = 48,
    StoneBricks = 49,
    Granite = 50,
    Diorite = 51,
    Andesite = 52,
    Calcite = 53,
    Tuff = 54,
    DripstoneBlock = 55,
    CobbledDeepslate = 56,
    PolishedDeepslate = 57,
    DeepslateBricks = 58,
    DeepslateTiles = 59,
    Blackstone = 60,
    PolishedBlackstone = 61,
    PolishedBlackstoneBricks = 62,
    CrimsonNylium = 63,
    WarpedNylium = 64,
    RedSand = 65,
    Sponge = 66,
    WetSponge = 67,
    LapisOre = 68,
    RedstoneOre = 69,
    EmeraldOre = 70,
    DiamondOre = 71,
    Lava = 72,
    WallTorch = 73,
    Fire = 74,
    SoulFire = 75,
    SoulTorch = 76,
    SoulWallTorch = 77,
    RedstoneTorch = 78,
    RedstoneWallTorch = 79,
    RedstoneLamp = 80,
    JackOLantern = 81,
    CarvedPumpkin = 82,
    Pumpkin = 83,
    Melon = 84,
    HayBlock = 85,
    SeaLantern = 86,
    Shroomlight = 87,
    CryingObsidian = 88,
    NetheriteBlock = 89,
    AncientDebris = 90,
    RespawnAnchor = 91,
    Target = 92,
    Lodestone = 93,
    HoneyBlock = 94,
    HoneycombBlock = 95,
    NetherGoldOre = 96,
    SoulSoil = 97,
    Basalt = 98,
    PolishedBasalt = 99,
    SmoothStone = 100,
    SmoothSandstone = 101,
    SmoothRedSandstone = 102,
    SmoothQuartz = 103,
    QuartzBlock = 104,
    ChiseledQuartzBlock = 105,
    QuartzPillar = 106,
    QuartzStairs = 107,
    Prismarine = 108,
    PrismarineBricks = 109,
    DarkPrismarine = 110,
    PurpurBlock = 111,
    PurpurPillar = 112,
    EndStone = 113,
    EndStoneBricks = 114,
    EndRod = 115,
    BoneBlock = 116,
    NetherBricks = 117,
    RedNetherBricks = 118,
    ShulkerBox = 119,
    WhiteShulkerBox = 120,
    OrangeShulkerBox = 121,
    MagentaShulkerBox = 122,
    LightBlueShulkerBox = 123,
    YellowShulkerBox = 124,
    LimeShulkerBox = 125,
    PinkShulkerBox = 126,
    GrayShulkerBox = 127,
    LightGrayShulkerBox = 128,
    CyanShulkerBox = 129,
    PurpleShulkerBox = 130,
    BlueShulkerBox = 131,
    BrownShulkerBox = 132,
    GreenShulkerBox = 133,
    RedShulkerBox = 134,
    BlackShulkerBox = 135,
    WhiteTerracotta = 136,
    OrangeTerracotta = 137,
    MagentaTerracotta = 138,
    LightBlueTerracotta = 139,
    YellowTerracotta = 140,
    LimeTerracotta = 141,
    PinkTerracotta = 142,
    GrayTerracotta = 143,
    LightGrayTerracotta = 144,
    CyanTerracotta = 145,
    PurpleTerracotta = 146,
    BlueTerracotta = 147,
    BrownTerracotta = 148,
    GreenTerracotta = 149,
    RedTerracotta = 150,
    BlackTerracotta = 151,
    Terracotta = 152,
    WhiteConcrete = 153,
    OrangeConcrete = 154,
    MagentaConcrete = 155,
    LightBlueConcrete = 156,
    YellowConcrete = 157,
    LimeConcrete = 158,
    PinkConcrete = 159,
    GrayConcrete = 160,
    LightGrayConcrete = 161,
    CyanConcrete = 162,
    PurpleConcrete = 163,
    BlueConcrete = 164,
    BrownConcrete = 165,
    GreenConcrete = 166,
    RedConcrete = 167,
    BlackConcrete = 168,
    WhiteConcretePowder = 169,
    OrangeConcretePowder = 170,
    MagentaConcretePowder = 171,
    LightBlueConcretePowder = 172,
    YellowConcretePowder = 173,
    LimeConcretePowder = 174,
    PinkConcretePowder = 175,
    GrayConcretePowder = 176,
    LightGrayConcretePowder = 177,
    CyanConcretePowder = 178,
    PurpleConcretePowder = 179,
    BlueConcretePowder = 180,
    BrownConcretePowder = 181,
    GreenConcretePowder = 182,
    RedConcretePowder = 183,
    BlackConcretePowder = 184,
    WhiteWool = 185,
    OrangeWool = 186,
    MagentaWool = 187,
    LightBlueWool = 188,
    YellowWool = 189,
    LimeWool = 190,
    PinkWool = 191,
    GrayWool = 192,
    LightGrayWool = 193,
    CyanWool = 194,
    PurpleWool = 195,
    BlueWool = 196,
    BrownWool = 197,
    GreenWool = 198,
    RedWool = 199,
    BlackWool = 200,
    WhiteCarpet = 201,
    OrangeCarpet = 202,
    MagentaCarpet = 203,
    LightBlueCarpet = 204,
    YellowCarpet = 205,
    LimeCarpet = 206,
    PinkCarpet = 207,
    GrayCarpet = 208,
    LightGrayCarpet = 209,
    CyanCarpet = 210,
    PurpleCarpet = 211,
    BlueCarpet = 212,
    BrownCarpet = 213,
    GreenCarpet = 214,
    RedCarpet = 215,
    BlackCarpet = 216,
    WhiteStainedGlass = 217,
    OrangeStainedGlass = 218,
    MagentaStainedGlass = 219,
    LightBlueStainedGlass = 220,
    YellowStainedGlass = 221,
    LimeStainedGlass = 222,
    PinkStainedGlass = 223,
    GrayStainedGlass = 224,
    LightGrayStainedGlass = 225,
    CyanStainedGlass = 226,
    PurpleStainedGlass = 227,
    BlueStainedGlass = 228,
    BrownStainedGlass = 229,
    GreenStainedGlass = 230,
    RedStainedGlass = 231,
    BlackStainedGlass = 232,
    TintedGlass = 233,
    AmethystBlock = 234,
    BuddingAmethyst = 235,
    AmethystCluster = 236,
    CopperOre = 237,
    CopperBlock = 238,
    ExposedCopper = 239,
    WeatheredCopper = 240,
    OxidizedCopper = 241,
    CutCopper = 242,
    ExposedCutCopper = 243,
    WeatheredCutCopper = 244,
    OxidizedCutCopper = 245,
    WaxedCopperBlock = 246,
    WaxedExposedCopper = 247,
    WaxedWeatheredCopper = 248,
    WaxedOxidizedCopper = 249,
    WaxedCutCopper = 250,
    WaxedExposedCutCopper = 251,
    WaxedWeatheredCutCopper = 252,
    WaxedOxidizedCutCopper = 253,
    RawCopperBlock = 254,
    RawIronBlock = 255,
    RawGoldBlock = 256,
    MangroveRoots = 257,
    MuddyMangroveRoots = 258,
    Mud = 259,
    PackedMud = 260,
    MudBricks = 261,
    MossBlock = 262,
    MossCarpet = 263,
    HangingRoots = 264,
    RootedDirt = 265,
    Azalea = 266,
    FloweringAzalea = 267,
    SporeBlossom = 268,
    Grass = 269,
    Fern = 270,
    DeadBush = 271,
    Dandelion = 272,
    Poppy = 273,
    BlueOrchid = 274,
    Allium = 275,
    AzureBluet = 276,
    RedTulip = 277,
    OrangeTulip = 278,
    WhiteTulip = 279,
    PinkTulip = 280,
    OxeyeDaisy = 281,
    Cornflower = 282,
    LilyOfTheValley = 283,
    WitherRose = 284,
    BrownMushroom = 285,
    RedMushroom = 286,
    CrimsonFungus = 287,
    WarpedFungus = 288,
    CrimsonRoots = 289,
    WarpedRoots = 290,
    NetherSprouts = 291,
    WeepingVines = 292,
    TwistingVines = 293,
    Vine = 294,
    GlowLichen = 295,
    LilyPad = 296,
    Seagrass = 297,
    TallSeagrass = 298,
    Kelp = 299,
    KelpPlant = 300,
    DriedKelpBlock = 301,
    TubeCoralBlock = 302,
    BrainCoralBlock = 303,
    BubbleCoralBlock = 304,
    FireCoralBlock = 305,
    HornCoralBlock = 306,
    DeadTubeCoralBlock = 307,
    DeadBrainCoralBlock = 308,
    DeadBubbleCoralBlock = 309,
    DeadFireCoralBlock = 310,
    DeadHornCoralBlock = 311,
    TubeCoral = 312,
    BrainCoral = 313,
    BubbleCoral = 314,
    FireCoral = 315,
    HornCoral = 316,
    DeadTubeCoral = 317,
    DeadBrainCoral = 318,
    DeadBubbleCoral = 319,
    DeadFireCoral = 320,
    DeadHornCoral = 321,
    TubeCoralFan = 322,
    BrainCoralFan = 323,
    BubbleCoralFan = 324,
    FireCoralFan = 325,
    HornCoralFan = 326,
    DeadTubeCoralFan = 327,
    DeadBrainCoralFan = 328,
    DeadBubbleCoralFan = 329,
    DeadFireCoralFan = 330,
    DeadHornCoralFan = 331,
    SeaPickle = 332,
    BlueIce = 333,
    PackedIce = 334,
    FrostedIce = 335,
    Snow2 = 336,
    PowderSnow = 337,
    OakSapling = 338,
    SpruceSapling = 339,
    BirchSapling = 340,
    JungleSapling = 341,
    AcaciaSapling = 342,
    DarkOakSapling = 343,
    CherrySapling = 344,
    OakLog2 = 345,
    SpruceLog = 346,
    BirchLog = 347,
    JungleLog = 348,
    AcaciaLog = 349,
    DarkOakLog = 350,
    CherryLog = 351,
    MangroveLog = 352,
    StrippedOakLog = 353,
    StrippedSpruceLog = 354,
    StrippedBirchLog = 355,
    StrippedJungleLog = 356,
    StrippedAcaciaLog = 357,
    StrippedDarkOakLog = 358,
    StrippedCherryLog = 359,
    StrippedMangroveLog = 360,
    OakWood = 361,
    SpruceWood = 362,
    BirchWood = 363,
    JungleWood = 364,
    AcaciaWood = 365,
    DarkOakWood = 366,
    CherryWood = 367,
    MangroveWood = 368,
    StrippedOakWood = 369,
    StrippedSpruceWood = 370,
    StrippedBirchWood = 371,
    StrippedJungleWood = 372,
    StrippedAcaciaWood = 373,
    StrippedDarkOakWood = 374,
    StrippedCherryWood = 375,
    StrippedMangroveWood = 376,
    OakPlanks2 = 377,
    SprucePlanks = 378,
    BirchPlanks = 379,
    JunglePlanks = 380,
    AcaciaPlanks = 381,
    DarkOakPlanks = 382,
    CherryPlanks = 383,
    MangrovePlanks = 384,
    BambooPlanks = 385,
    BambooMosaic = 386,
    OakLeaves2 = 387,
    SpruceLeaves = 388,
    BirchLeaves = 389,
    JungleLeaves = 390,
    AcaciaLeaves = 391,
    DarkOakLeaves = 392,
    CherryLeaves = 393,
    MangroveLeaves = 394,
    AzaleaLeaves = 395,
    FloweringAzaleaLeaves = 396,
    Cactus = 397,
    SugarCane = 398,
    Mycelium = 399,
    MushroomStem = 400,
    StoneSlab = 403,
    OakSlab = 404,
    RedMushroomBlock = 401,
    BrownMushroomBlock = 402,
    StoneStairs = 405,
    OakStairs = 406,
}

impl BlockId {
    pub const fn name(&self) -> &'static str {
        match self {
            BlockId::Air => "Air",
            BlockId::Stone => "Stone",
            BlockId::GrassBlock => "Grass",
            BlockId::Dirt => "Dirt",
            BlockId::Cobblestone => "Cobble",
            BlockId::OakPlanks => "Planks",
            BlockId::Bedrock => "Bedrock",
            BlockId::Water => "Water",
            BlockId::Sand => "Sand",
            BlockId::Gravel => "Gravel",
            BlockId::GoldOre => "GoldOre",
            BlockId::IronOre => "IronOre",
            BlockId::CoalOre => "CoalOre",
            BlockId::OakLog => "OakLog",
            BlockId::OakLeaves => "Leaves",
            BlockId::Glass => "Glass",
            BlockId::CraftingTable => "C.Table",
            BlockId::Furnace => "Furnace",
            BlockId::Chest => "Chest",
            BlockId::Torch => "Torch",
            BlockId::Bricks => "Bricks",
            BlockId::StoneBricks => "StBrick",
            BlockId::SnowBlock => "Snow",
            BlockId::GoldBlock => "Gold",
            BlockId::IronBlock => "Iron",
            BlockId::DiamondBlock => "Diamond",
            BlockId::LapisBlock => "Lapis",
            BlockId::Bookshelf => "Books",
            BlockId::Netherrack => "Nether",
            BlockId::Obsidian => "Obsid",
            BlockId::Sponge => "Sponge",
            BlockId::HayBlock => "Hay",
            BlockId::Melon => "Melon",
            BlockId::Pumpkin => "Pumpkin",
            BlockId::Deepslate => "Deepslate",
            BlockId::Granite => "Granite",
            BlockId::Diorite => "Diorite",
            BlockId::Andesite => "Andesite",
            BlockId::Sandstone => "Sandstone",
            BlockId::Snow => "Snow",
            BlockId::Ice => "Ice",
            BlockId::Lava => "Lava",
            BlockId::Grass => "TallGrass",
            BlockId::Fern => "Fern",
            BlockId::DeadBush => "DeadBush",
            BlockId::Dandelion => "Dandelion",
            BlockId::Poppy => "Poppy",
            BlockId::BlueOrchid => "BlueOrchid",
            BlockId::OxeyeDaisy => "OxeyeDaisy",
            BlockId::Cornflower => "Cornflower",
            BlockId::RedTulip => "RedTulip",
            BlockId::BrownMushroom => "B.Mushroom",
            BlockId::RedMushroom => "R.Mushroom",
            BlockId::Cactus => "Cactus",
            BlockId::SugarCane => "SugarCane",
            BlockId::Vine => "Vine",
            BlockId::LilyPad => "LilyPad",
            BlockId::OakSapling => "Sapling",
            BlockId::SpruceSapling => "SpruceSap",
            BlockId::BirchSapling => "BirchSap",
            BlockId::JungleSapling => "JungleSap",
            BlockId::AcaciaSapling => "AcaciaSap",
            BlockId::DarkOakSapling => "DarkOakSap",
            BlockId::SpruceLog => "SpruceLog",
            BlockId::BirchLog => "BirchLog",
            BlockId::JungleLog => "JungleLog",
            BlockId::AcaciaLog => "AcaciaLog",
            BlockId::DarkOakLog => "DarkOakLog",
            BlockId::SpruceLeaves => "SpruceLvs",
            BlockId::BirchLeaves => "BirchLvs",
            BlockId::JungleLeaves => "JungleLvs",
            BlockId::AcaciaLeaves => "AcaciaLvs",
            BlockId::DarkOakLeaves => "DarkOakLvs",
            BlockId::SprucePlanks => "SprcPlank",
            BlockId::BirchPlanks => "BrchPlank",
            BlockId::JunglePlanks => "JnglPlank",
            BlockId::AcaciaPlanks => "AcacPlank",
            BlockId::DarkOakPlanks => "DrkPlank",
            BlockId::MossyCobblestone => "MossCobble",
            BlockId::CobbledDeepslate => "CblDeepsl",
            BlockId::PolishedDeepslate => "PolDeepsl",
            BlockId::DeepslateBricks => "DpBricks",
            BlockId::DeepslateTiles => "DpTiles",
            BlockId::DeepslateCoalOre => "DpCoal",
            BlockId::DeepslateIronOre => "DpIron",
            BlockId::DeepslateGoldOre => "DpGold",
            BlockId::DeepslateDiamondOre => "DpDiamond",
            BlockId::DeepslateRedstoneOre => "DpRedstn",
            BlockId::DeepslateLapisOre => "DpLapis",
            BlockId::DeepslateEmeraldOre => "DpEmerald",
            BlockId::DiamondOre => "DiamondOre",
            BlockId::RedstoneOre => "RedstnOre",
            BlockId::LapisOre => "LapisOre",
            BlockId::EmeraldOre => "EmeraldOre",
            BlockId::CopperOre => "CopperOre",
            BlockId::CopperBlock => "Copper",
            BlockId::RawIronBlock => "RawIron",
            BlockId::RawGoldBlock => "RawGold",
            BlockId::RawCopperBlock => "RawCopper",
            BlockId::AmethystBlock => "Amethyst",
            BlockId::Tuff => "Tuff",
            BlockId::Calcite => "Calcite",
            BlockId::DripstoneBlock => "Dripstone",
            BlockId::Glowstone => "Glowstone",
            BlockId::SeaLantern => "SeaLantern",
            BlockId::Shroomlight => "Shroomlight",
            BlockId::JackOLantern => "JackOLant",
            BlockId::CarvedPumpkin => "CrvdPumpk",
            BlockId::RedstoneLamp => "RstnLamp",
            BlockId::SoulSand => "SoulSand",
            BlockId::SoulSoil => "SoulSoil",
            BlockId::RedSand => "RedSand",
            BlockId::Prismarine => "Prismarin",
            BlockId::PrismarineBricks => "PrismBrik",
            BlockId::DarkPrismarine => "DkPrism",
            BlockId::Spawner => "Spawner",
            BlockId::MushroomStem => "MshrmStem",
            BlockId::RedMushroomBlock => "RedMshCap",
            BlockId::BrownMushroomBlock => "BrnMshCap",
            BlockId::StoneSlab => "StnSlab",
            BlockId::OakSlab => "OakSlab",
            BlockId::StoneStairs => "StnStair",
            BlockId::OakStairs => "OakStair",
            BlockId::WhiteCarpet => "WhtCarpet",
            BlockId::RedCarpet => "RedCarpet",
            BlockId::RedWool => "RedWool",
            BlockId::WhiteWool => "WhiteWool",
            BlockId::CryingObsidian => "CryObsid",
            BlockId::BoneBlock => "BoneBlock",
            BlockId::NetherBricks => "NetherBri",
            BlockId::RedNetherBricks => "RedNethrB",
            BlockId::EndStone => "EndStone",
            BlockId::PurpurBlock => "Purpur",
            BlockId::MossBlock => "Moss",
            BlockId::Podzol => "Podzol",
            BlockId::CoarseDirt => "CrsDirt",
            BlockId::Mycelium => "Mycelium",
            BlockId::Mud => "Mud",
            BlockId::PackedMud => "PckdMud",
            BlockId::MudBricks => "MudBricks",
            BlockId::MangroveRoots => "MngrRoots",
            BlockId::MuddyMangroveRoots => "MdyRoots",
            BlockId::Terracotta => "Terracotta",
            BlockId::WhiteTerracotta => "WhtTerrac",
            BlockId::Blackstone => "Blackston",
            BlockId::PolishedBlackstone => "PolBlack",
            BlockId::PolishedBlackstoneBricks => "PolBlkBri",
            BlockId::CrimsonNylium => "CrimNylium",
            BlockId::WarpedNylium => "WarpNylium",
            BlockId::Basalt => "Basalt",
            BlockId::PolishedBasalt => "PolBasalt",
            BlockId::SmoothStone => "SmthStone",
            BlockId::SmoothSandstone => "SmthSand",
            BlockId::SmoothQuartz => "SmthQuart",
            BlockId::QuartzBlock => "Quartz",
            BlockId::ChiseledQuartzBlock => "ChslQuart",
            BlockId::QuartzPillar => "QrtzPilar",
            _ => "?",
        }
    }

    pub fn from_name(s: &str) -> Option<Self> {
        let lower = s.to_lowercase();
        match lower.as_str() {
            "air" => Some(BlockId::Air),
            "stone" => Some(BlockId::Stone),
            "grass" | "grass_block" => Some(BlockId::GrassBlock),
            "dirt" => Some(BlockId::Dirt),
            "cobblestone" | "cobble" => Some(BlockId::Cobblestone),
            "oak_planks" | "planks" => Some(BlockId::OakPlanks),
            "bedrock" => Some(BlockId::Bedrock),
            "water" => Some(BlockId::Water),
            "sand" => Some(BlockId::Sand),
            "gravel" => Some(BlockId::Gravel),
            "gold_ore" => Some(BlockId::GoldOre),
            "iron_ore" => Some(BlockId::IronOre),
            "coal_ore" => Some(BlockId::CoalOre),
            "oak_log" => Some(BlockId::OakLog),
            "oak_leaves" | "leaves" => Some(BlockId::OakLeaves),
            "glass" => Some(BlockId::Glass),
            "crafting_table" => Some(BlockId::CraftingTable),
            "furnace" => Some(BlockId::Furnace),
            "chest" => Some(BlockId::Chest),
            "torch" => Some(BlockId::Torch),
            "bricks" => Some(BlockId::Bricks),
            "stone_bricks" | "stonebricks" => Some(BlockId::StoneBricks),
            "snow_block" | "snow" => Some(BlockId::SnowBlock),
            "gold_block" => Some(BlockId::GoldBlock),
            "iron_block" => Some(BlockId::IronBlock),
            "diamond_block" => Some(BlockId::DiamondBlock),
            "lapis_block" => Some(BlockId::LapisBlock),
            "bookshelf" => Some(BlockId::Bookshelf),
            "netherrack" => Some(BlockId::Netherrack),
            "obsidian" => Some(BlockId::Obsidian),
            "sponge" => Some(BlockId::Sponge),
            "hay_block" => Some(BlockId::HayBlock),
            "melon" => Some(BlockId::Melon),
            "pumpkin" => Some(BlockId::Pumpkin),
            "deepslate" => Some(BlockId::Deepslate),
            "granite" => Some(BlockId::Granite),
            "diorite" => Some(BlockId::Diorite),
            "andesite" => Some(BlockId::Andesite),
            "sandstone" => Some(BlockId::Sandstone),
            "lava" => Some(BlockId::Lava),
            "cactus" => Some(BlockId::Cactus),
            "sugar_cane" | "sugarcane" => Some(BlockId::SugarCane),
            "vine" | "vines" => Some(BlockId::Vine),
            "lily_pad" => Some(BlockId::LilyPad),
            "mossy_cobblestone" => Some(BlockId::MossyCobblestone),
            "cobbled_deepslate" => Some(BlockId::CobbledDeepslate),
            "glowstone" => Some(BlockId::Glowstone),
            "sea_lantern" => Some(BlockId::SeaLantern),
            "shroomlight" => Some(BlockId::Shroomlight),
            "jack_o_lantern" => Some(BlockId::JackOLantern),
            "redstone_lamp" => Some(BlockId::RedstoneLamp),
            "soul_sand" => Some(BlockId::SoulSand),
            "soul_soil" => Some(BlockId::SoulSoil),
            "red_sand" => Some(BlockId::RedSand),
            "prismarine" => Some(BlockId::Prismarine),
            "spawner" => Some(BlockId::Spawner),
            "nether_bricks" => Some(BlockId::NetherBricks),
            "end_stone" => Some(BlockId::EndStone),
            "moss_block" => Some(BlockId::MossBlock),
            "podzol" => Some(BlockId::Podzol),
            "coarse_dirt" => Some(BlockId::CoarseDirt),
            "mycelium" => Some(BlockId::Mycelium),
            "mud" => Some(BlockId::Mud),
            "terracotta" => Some(BlockId::Terracotta),
            "blackstone" => Some(BlockId::Blackstone),
            "basalt" => Some(BlockId::Basalt),
            "smooth_stone" => Some(BlockId::SmoothStone),
            "quartz_block" => Some(BlockId::QuartzBlock),
            "bone_block" => Some(BlockId::BoneBlock),
            "purpur_block" => Some(BlockId::PurpurBlock),
            _ => None,
        }
    }

    pub fn is_solid(&self) -> bool {
        !matches!(self,
            BlockId::Air | BlockId::Water | BlockId::Lava | BlockId::Torch |
            BlockId::WallTorch | BlockId::Fire | BlockId::SoulFire |
            BlockId::Grass | BlockId::Fern | BlockId::DeadBush |
            BlockId::Dandelion | BlockId::Poppy | BlockId::BlueOrchid |
            BlockId::Allium | BlockId::AzureBluet | BlockId::RedTulip |
            BlockId::OrangeTulip | BlockId::WhiteTulip | BlockId::PinkTulip |
            BlockId::OxeyeDaisy | BlockId::Cornflower | BlockId::LilyOfTheValley |
            BlockId::WitherRose | BlockId::BrownMushroom | BlockId::RedMushroom |
            BlockId::CrimsonFungus | BlockId::WarpedFungus |
            BlockId::CrimsonRoots | BlockId::WarpedRoots | BlockId::NetherSprouts |
            BlockId::WeepingVines | BlockId::TwistingVines | BlockId::Vine |
            BlockId::GlowLichen | BlockId::LilyPad | BlockId::Seagrass |
            BlockId::TallSeagrass | BlockId::KelpPlant |
            BlockId::SporeBlossom | BlockId::Azalea | BlockId::FloweringAzalea |
            BlockId::MossCarpet | BlockId::HangingRoots |
            BlockId::OakSapling | BlockId::SpruceSapling | BlockId::BirchSapling |
            BlockId::Cactus | BlockId::SugarCane |
            BlockId::JungleSapling | BlockId::AcaciaSapling | BlockId::DarkOakSapling |
            BlockId::CherrySapling
        )
    }

    pub fn is_crossed(&self) -> bool {
        matches!(self,
            BlockId::Grass | BlockId::Fern | BlockId::DeadBush |
            BlockId::Dandelion | BlockId::Poppy | BlockId::BlueOrchid |
            BlockId::Allium | BlockId::AzureBluet | BlockId::RedTulip |
            BlockId::OrangeTulip | BlockId::WhiteTulip | BlockId::PinkTulip |
            BlockId::OxeyeDaisy | BlockId::Cornflower | BlockId::LilyOfTheValley |
            BlockId::WitherRose | BlockId::BrownMushroom | BlockId::RedMushroom |
            BlockId::CrimsonFungus | BlockId::WarpedFungus |
            BlockId::CrimsonRoots | BlockId::WarpedRoots | BlockId::NetherSprouts |
            BlockId::OakSapling | BlockId::SpruceSapling | BlockId::BirchSapling |
            BlockId::JungleSapling | BlockId::AcaciaSapling | BlockId::DarkOakSapling |
            BlockId::CherrySapling |
            BlockId::SugarCane | BlockId::Cactus |
            BlockId::LilyPad |
            BlockId::Vine | BlockId::WeepingVines | BlockId::TwistingVines |
            BlockId::GlowLichen
        )
    }

    pub fn is_transparent(&self) -> bool {
        matches!(self,
            BlockId::Air | BlockId::Water | BlockId::Lava |
            BlockId::Glass | BlockId::OakLeaves | BlockId::SpruceLeaves |
            BlockId::BirchLeaves | BlockId::JungleLeaves | BlockId::AcaciaLeaves |
            BlockId::DarkOakLeaves | BlockId::CherryLeaves | BlockId::MangroveLeaves |
            BlockId::AzaleaLeaves | BlockId::FloweringAzaleaLeaves | BlockId::Ice |
            BlockId::TintedGlass | BlockId::WhiteStainedGlass | BlockId::OrangeStainedGlass |
            BlockId::MagentaStainedGlass | BlockId::LightBlueStainedGlass |
            BlockId::YellowStainedGlass | BlockId::LimeStainedGlass | BlockId::PinkStainedGlass |
            BlockId::GrayStainedGlass | BlockId::LightGrayStainedGlass | BlockId::CyanStainedGlass |
            BlockId::PurpleStainedGlass | BlockId::BlueStainedGlass | BlockId::BrownStainedGlass |
            BlockId::GreenStainedGlass | BlockId::RedStainedGlass | BlockId::BlackStainedGlass |
            BlockId::Snow | BlockId::SnowBlock | BlockId::PowderSnow |
            BlockId::Glowstone | BlockId::RedstoneLamp | BlockId::SeaLantern |
            BlockId::Shroomlight | BlockId::JackOLantern |
            BlockId::Grass | BlockId::Fern | BlockId::DeadBush |
            BlockId::Dandelion | BlockId::Poppy | BlockId::BlueOrchid |
            BlockId::Allium | BlockId::AzureBluet | BlockId::RedTulip |
            BlockId::OrangeTulip | BlockId::WhiteTulip | BlockId::PinkTulip |
            BlockId::OxeyeDaisy | BlockId::Cornflower | BlockId::LilyOfTheValley |
            BlockId::WitherRose | BlockId::BrownMushroom | BlockId::RedMushroom |
            BlockId::CrimsonFungus | BlockId::WarpedFungus |
            BlockId::CrimsonRoots | BlockId::WarpedRoots | BlockId::NetherSprouts |
            BlockId::OakSapling | BlockId::SpruceSapling | BlockId::BirchSapling |
            BlockId::JungleSapling | BlockId::AcaciaSapling | BlockId::DarkOakSapling |
            BlockId::CherrySapling | BlockId::Vine |
            BlockId::WeepingVines | BlockId::TwistingVines |
            BlockId::GlowLichen | BlockId::LilyPad | BlockId::Seagrass |
            BlockId::TallSeagrass | BlockId::KelpPlant |
            BlockId::SporeBlossom | BlockId::Azalea | BlockId::FloweringAzalea |
            BlockId::MossCarpet | BlockId::HangingRoots
        )
    }

    pub fn is_slab(&self) -> bool {
        matches!(self, BlockId::StoneSlab | BlockId::OakSlab)
    }

    pub fn is_stair(&self) -> bool {
        matches!(self, BlockId::StoneStairs | BlockId::OakStairs)
    }

    #[allow(dead_code)]
    pub fn light_level(&self) -> u8 {
        match self {
            BlockId::Torch | BlockId::WallTorch => 14,
            BlockId::Glowstone | BlockId::Shroomlight | BlockId::SeaLantern => 15,
            BlockId::Fire | BlockId::SoulFire => 15,
            BlockId::SoulTorch | BlockId::SoulWallTorch => 10,
            BlockId::RedstoneTorch => 7,
            BlockId::JackOLantern => 10,
            BlockId::Lava => 15,
            BlockId::RedstoneLamp => 15,
            BlockId::Furnace => 13,
            _ => 0,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum BlockFace {
    Top,
    Bottom,
    Left,
    Right,
    Front,
    Back,
}

pub const FACES: [BlockFace; 6] = [
    BlockFace::Top,
    BlockFace::Bottom,
    BlockFace::Left,
    BlockFace::Right,
    BlockFace::Front,
    BlockFace::Back,
];

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Block {
    pub id: BlockId,
    pub data: u8,
}

impl Block {
    pub const fn new(id: BlockId) -> Self {
        Block { id, data: 0 }
    }

    pub const fn air() -> Self {
        Block { id: BlockId::Air, data: 0 }
    }

    pub fn is_air(&self) -> bool {
        matches!(self.id, BlockId::Air)
    }
}
