#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u16)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    GrassBlock = 2,
    Dirt = 3,
    Cobblestone = 4,
    OakPlanks = 5,
    Bedrock = 6,
    Water = 7,
    Sand = 8,
    Gravel = 9,
    GoldOre = 10,
    IronOre = 11,
    CoalOre = 12,
    OakLog = 13,
    OakLeaves = 14,
    Glass = 15,
    CraftingTable = 16,
    Furnace = 17,
    Chest = 18,
    Torch = 19,
    Snow = 20,
    Ice = 21,
    Glowstone = 22,
    Netherrack = 23,
    SoulSand = 24,
    Deepslate = 25,
    SnowBlock = 26,
    CoarseDirt = 27,
    Podzol = 28,
    DeepslateIronOre = 29,
    DeepslateCoalOre = 30,
    DeepslateGoldOre = 31,
    DeepslateRedstoneOre = 32,
    DeepslateDiamondOre = 33,
    DeepslateEmeraldOre = 34,
    DeepslateLapisOre = 35,
    DeepslateCopperOre = 36,
    DiamondBlock = 37,
    IronBlock = 38,
    GoldBlock = 39,
    EmeraldBlock = 40,
    LapisBlock = 41,
    RedstoneBlock = 42,
    Bricks = 43,
    Bookshelf = 44,
    MossyCobblestone = 45,
    Obsidian = 46,
    Spawner = 47,
    Sandstone = 48,
    StoneBricks = 49,
    Granite = 50,
    Diorite = 51,
    Andesite = 52,
    Calcite = 53,
    Tuff = 54,
    DripstoneBlock = 55,
    CobbledDeepslate = 56,
    PolishedDeepslate = 57,
    DeepslateBricks = 58,
    DeepslateTiles = 59,
    Blackstone = 60,
    PolishedBlackstone = 61,
    PolishedBlackstoneBricks = 62,
    CrimsonNylium = 63,
    WarpedNylium = 64,
    RedSand = 65,
    Sponge = 66,
    WetSponge = 67,
    LapisOre = 68,
    RedstoneOre = 69,
    EmeraldOre = 70,
    DiamondOre = 71,
    Lava = 72,
    WallTorch = 73,
    Fire = 74,
    SoulFire = 75,
    SoulTorch = 76,
    SoulWallTorch = 77,
    RedstoneTorch = 78,
    RedstoneWallTorch = 79,
    RedstoneLamp = 80,
    JackOLantern = 81,
    CarvedPumpkin = 82,
    Pumpkin = 83,
    Melon = 84,
    HayBlock = 85,
    SeaLantern = 86,
    Shroomlight = 87,
    CryingObsidian = 88,
    NetheriteBlock = 89,
    AncientDebris = 90,
    RespawnAnchor = 91,
    Target = 92,
    Lodestone = 93,
    HoneyBlock = 94,
    HoneycombBlock = 95,
    NetherGoldOre = 96,
    SoulSoil = 97,
    Basalt = 98,
    PolishedBasalt = 99,
    SmoothStone = 100,
    SmoothSandstone = 101,
    SmoothRedSandstone = 102,
    SmoothQuartz = 103,
    QuartzBlock = 104,
    ChiseledQuartzBlock = 105,
    QuartzPillar = 106,
    QuartzStairs = 107,
    Prismarine = 108,
    PrismarineBricks = 109,
    DarkPrismarine = 110,
    PurpurBlock = 111,
    PurpurPillar = 112,
    EndStone = 113,
    EndStoneBricks = 114,
    EndRod = 115,
    BoneBlock = 116,
    NetherBricks = 117,
    RedNetherBricks = 118,
    ShulkerBox = 119,
    WhiteShulkerBox = 120,
    OrangeShulkerBox = 121,
    MagentaShulkerBox = 122,
    LightBlueShulkerBox = 123,
    YellowShulkerBox = 124,
    LimeShulkerBox = 125,
    PinkShulkerBox = 126,
    GrayShulkerBox = 127,
    LightGrayShulkerBox = 128,
    CyanShulkerBox = 129,
    PurpleShulkerBox = 130,
    BlueShulkerBox = 131,
    BrownShulkerBox = 132,
    GreenShulkerBox = 133,
    RedShulkerBox = 134,
    BlackShulkerBox = 135,
    WhiteTerracotta = 136,
    OrangeTerracotta = 137,
    MagentaTerracotta = 138,
    LightBlueTerracotta = 139,
    YellowTerracotta = 140,
    LimeTerracotta = 141,
    PinkTerracotta = 142,
    GrayTerracotta = 143,
    LightGrayTerracotta = 144,
    CyanTerracotta = 145,
    PurpleTerracotta = 146,
    BlueTerracotta = 147,
    BrownTerracotta = 148,
    GreenTerracotta = 149,
    RedTerracotta = 150,
    BlackTerracotta = 151,
    Terracotta = 152,
    WhiteConcrete = 153,
    OrangeConcrete = 154,
    MagentaConcrete = 155,
    LightBlueConcrete = 156,
    YellowConcrete = 157,
    LimeConcrete = 158,
    PinkConcrete = 159,
    GrayConcrete = 160,
    LightGrayConcrete = 161,
    CyanConcrete = 162,
    PurpleConcrete = 163,
    BlueConcrete = 164,
    BrownConcrete = 165,
    GreenConcrete = 166,
    RedConcrete = 167,
    BlackConcrete = 168,
    WhiteConcretePowder = 169,
    OrangeConcretePowder = 170,
    MagentaConcretePowder = 171,
    LightBlueConcretePowder = 172,
    YellowConcretePowder = 173,
    LimeConcretePowder = 174,
    PinkConcretePowder = 175,
    GrayConcretePowder = 176,
    LightGrayConcretePowder = 177,
    CyanConcretePowder = 178,
    PurpleConcretePowder = 179,
    BlueConcretePowder = 180,
    BrownConcretePowder = 181,
    GreenConcretePowder = 182,
    RedConcretePowder = 183,
    BlackConcretePowder = 184,
    WhiteWool = 185,
    OrangeWool = 186,
    MagentaWool = 187,
    LightBlueWool = 188,
    YellowWool = 189,
    LimeWool = 190,
    PinkWool = 191,
    GrayWool = 192,
    LightGrayWool = 193,
    CyanWool = 194,
    PurpleWool = 195,
    BlueWool = 196,
    BrownWool = 197,
    GreenWool = 198,
    RedWool = 199,
    BlackWool = 200,
    WhiteCarpet = 201,
    OrangeCarpet = 202,
    MagentaCarpet = 203,
    LightBlueCarpet = 204,
    YellowCarpet = 205,
    LimeCarpet = 206,
    PinkCarpet = 207,
    GrayCarpet = 208,
    LightGrayCarpet = 209,
    CyanCarpet = 210,
    PurpleCarpet = 211,
    BlueCarpet = 212,
    BrownCarpet = 213,
    GreenCarpet = 214,
    RedCarpet = 215,
    BlackCarpet = 216,
    WhiteStainedGlass = 217,
    OrangeStainedGlass = 218,
    MagentaStainedGlass = 219,
    LightBlueStainedGlass = 220,
    YellowStainedGlass = 221,
    LimeStainedGlass = 222,
    PinkStainedGlass = 223,
    GrayStainedGlass = 224,
    LightGrayStainedGlass = 225,
    CyanStainedGlass = 226,
    PurpleStainedGlass = 227,
    BlueStainedGlass = 228,
    BrownStainedGlass = 229,
    GreenStainedGlass = 230,
    RedStainedGlass = 231,
    BlackStainedGlass = 232,
    TintedGlass = 233,
    AmethystBlock = 234,
    BuddingAmethyst = 235,
    AmethystCluster = 236,
    CopperOre = 237,
    CopperBlock = 238,
    ExposedCopper = 239,
    WeatheredCopper = 240,
    OxidizedCopper = 241,
    CutCopper = 242,
    ExposedCutCopper = 243,
    WeatheredCutCopper = 244,
    OxidizedCutCopper = 245,
    WaxedCopperBlock = 246,
    WaxedExposedCopper = 247,
    WaxedWeatheredCopper = 248,
    WaxedOxidizedCopper = 249,
    WaxedCutCopper = 250,
    WaxedExposedCutCopper = 251,
    WaxedWeatheredCutCopper = 252,
    WaxedOxidizedCutCopper = 253,
    RawCopperBlock = 254,
    RawIronBlock = 255,
    RawGoldBlock = 256,
    MangroveRoots = 257,
    MuddyMangroveRoots = 258,
    Mud = 259,
    PackedMud = 260,
    MudBricks = 261,
    MossBlock = 262,
    MossCarpet = 263,
    HangingRoots = 264,
    RootedDirt = 265,
    Azalea = 266,
    FloweringAzalea = 267,
    SporeBlossom = 268,
    Grass = 269,
    Fern = 270,
    DeadBush = 271,
    Dandelion = 272,
    Poppy = 273,
    BlueOrchid = 274,
    Allium = 275,
    AzureBluet = 276,
    RedTulip = 277,
    OrangeTulip = 278,
    WhiteTulip = 279,
    PinkTulip = 280,
    OxeyeDaisy = 281,
    Cornflower = 282,
    LilyOfTheValley = 283,
    WitherRose = 284,
    BrownMushroom = 285,
    RedMushroom = 286,
    CrimsonFungus = 287,
    WarpedFungus = 288,
    CrimsonRoots = 289,
    WarpedRoots = 290,
    NetherSprouts = 291,
    WeepingVines = 292,
    TwistingVines = 293,
    Vine = 294,
    GlowLichen = 295,
    LilyPad = 296,
    Seagrass = 297,
    TallSeagrass = 298,
    Kelp = 299,
    KelpPlant = 300,
    DriedKelpBlock = 301,
    TubeCoralBlock = 302,
    BrainCoralBlock = 303,
    BubbleCoralBlock = 304,
    FireCoralBlock = 305,
    HornCoralBlock = 306,
    DeadTubeCoralBlock = 307,
    DeadBrainCoralBlock = 308,
    DeadBubbleCoralBlock = 309,
    DeadFireCoralBlock = 310,
    DeadHornCoralBlock = 311,
    TubeCoral = 312,
    BrainCoral = 313,
    BubbleCoral = 314,
    FireCoral = 315,
    HornCoral = 316,
    DeadTubeCoral = 317,
    DeadBrainCoral = 318,
    DeadBubbleCoral = 319,
    DeadFireCoral = 320,
    DeadHornCoral = 321,
    TubeCoralFan = 322,
    BrainCoralFan = 323,
    BubbleCoralFan = 324,
    FireCoralFan = 325,
    HornCoralFan = 326,
    DeadTubeCoralFan = 327,
    DeadBrainCoralFan = 328,
    DeadBubbleCoralFan = 329,
    DeadFireCoralFan = 330,
    DeadHornCoralFan = 331,
    SeaPickle = 332,
    BlueIce = 333,
    PackedIce = 334,
    FrostedIce = 335,
    Snow2 = 336,
    PowderSnow = 337,
    OakSapling = 338,
    SpruceSapling = 339,
    BirchSapling = 340,
    JungleSapling = 341,
    AcaciaSapling = 342,
    DarkOakSapling = 343,
    CherrySapling = 344,
    OakLog2 = 345,
    SpruceLog = 346,
    BirchLog = 347,
    JungleLog = 348,
    AcaciaLog = 349,
    DarkOakLog = 350,
    CherryLog = 351,
    MangroveLog = 352,
    StrippedOakLog = 353,
    StrippedSpruceLog = 354,
    StrippedBirchLog = 355,
    StrippedJungleLog = 356,
    StrippedAcaciaLog = 357,
    StrippedDarkOakLog = 358,
    StrippedCherryLog = 359,
    StrippedMangroveLog = 360,
    OakWood = 361,
    SpruceWood = 362,
    BirchWood = 363,
    JungleWood = 364,
    AcaciaWood = 365,
    DarkOakWood = 366,
    CherryWood = 367,
    MangroveWood = 368,
    StrippedOakWood = 369,
    StrippedSpruceWood = 370,
    StrippedBirchWood = 371,
    StrippedJungleWood = 372,
    StrippedAcaciaWood = 373,
    StrippedDarkOakWood = 374,
    StrippedCherryWood = 375,
    StrippedMangroveWood = 376,
    OakPlanks2 = 377,
    SprucePlanks = 378,
    BirchPlanks = 379,
    JunglePlanks = 380,
    AcaciaPlanks = 381,
    DarkOakPlanks = 382,
    CherryPlanks = 383,
    MangrovePlanks = 384,
    BambooPlanks = 385,
    BambooMosaic = 386,
    OakLeaves2 = 387,
    SpruceLeaves = 388,
    BirchLeaves = 389,
    JungleLeaves = 390,
    AcaciaLeaves = 391,
    DarkOakLeaves = 392,
    CherryLeaves = 393,
    MangroveLeaves = 394,
    AzaleaLeaves = 395,
    FloweringAzaleaLeaves = 396,
    Cactus = 397,
    SugarCane = 398,
    Mycelium = 399,
    MushroomStem = 400,
    StoneSlab = 403,
    OakSlab = 404,
    RedMushroomBlock = 401,
    BrownMushroomBlock = 402,
    StoneStairs = 405,
    OakStairs = 406,
    MagmaBlock = 407,
    Ladder = 408,
    SweetBerryBush = 409,
    Bamboo = 410,
    OakDoor = 411,
    OakFence = 412,
    RedstoneDust = 413,
}

macro_rules! bitmask {
    ($($variant:ident),* $(,)?) => {{
        let mut m = [0u64; 7];
        $(
            let d = BlockId::$variant as u16;
            m[(d / 64) as usize] |= 1u64 << (d as u64 % 64);
        )*
        m
    }};
}

const NON_SOLID_BITMASK: [u64; 7] = bitmask!(
    Air, Water, Lava, OakDoor, RedstoneDust,
    Torch, WallTorch, SoulTorch, SoulWallTorch, RedstoneTorch, RedstoneWallTorch,
    Fire, SoulFire, EndRod, AmethystCluster,
    Glass, TintedGlass,
    WhiteStainedGlass, OrangeStainedGlass, MagentaStainedGlass, LightBlueStainedGlass,
    YellowStainedGlass, LimeStainedGlass, PinkStainedGlass, GrayStainedGlass,
    LightGrayStainedGlass, CyanStainedGlass, PurpleStainedGlass, BlueStainedGlass,
    BrownStainedGlass, GreenStainedGlass, RedStainedGlass, BlackStainedGlass,
    OakLeaves, OakLeaves2, SpruceLeaves, BirchLeaves, JungleLeaves, AcaciaLeaves,
    DarkOakLeaves, CherryLeaves, MangroveLeaves, AzaleaLeaves, FloweringAzaleaLeaves,
    Ice, Snow, Snow2, PowderSnow,
    StoneSlab, OakSlab, StoneStairs, OakStairs,
    Grass, Fern, DeadBush, Dandelion, Poppy, BlueOrchid, Allium, AzureBluet,
    RedTulip, OrangeTulip, WhiteTulip, PinkTulip, OxeyeDaisy, Cornflower,
    LilyOfTheValley, WitherRose, BrownMushroom, RedMushroom,
    CrimsonFungus, WarpedFungus, CrimsonRoots, WarpedRoots, NetherSprouts,
    WeepingVines, TwistingVines, Vine, GlowLichen, LilyPad,
    Seagrass, TallSeagrass, Kelp, KelpPlant,
    SporeBlossom, Azalea, FloweringAzalea, MossCarpet, HangingRoots,
    OakSapling, SpruceSapling, BirchSapling, SugarCane,
    JungleSapling, AcaciaSapling, DarkOakSapling, CherrySapling,
    Ladder, SweetBerryBush, Cactus, Bamboo, SeaPickle,
    TubeCoral, BrainCoral, BubbleCoral, FireCoral, HornCoral,
    DeadTubeCoral, DeadBrainCoral, DeadBubbleCoral, DeadFireCoral, DeadHornCoral,
    TubeCoralFan, BrainCoralFan, BubbleCoralFan, FireCoralFan, HornCoralFan,
    DeadTubeCoralFan, DeadBrainCoralFan, DeadBubbleCoralFan, DeadFireCoralFan, DeadHornCoralFan,
);

const TRANSPARENT_BITMASK: [u64; 7] = bitmask!(
    Air, Water, Lava,
    Glass, TintedGlass,
    WhiteStainedGlass, OrangeStainedGlass, MagentaStainedGlass, LightBlueStainedGlass,
    YellowStainedGlass, LimeStainedGlass, PinkStainedGlass, GrayStainedGlass,
    LightGrayStainedGlass, CyanStainedGlass, PurpleStainedGlass, BlueStainedGlass,
    BrownStainedGlass, GreenStainedGlass, RedStainedGlass, BlackStainedGlass,
    OakLeaves, OakLeaves2, SpruceLeaves, BirchLeaves, JungleLeaves, AcaciaLeaves,
    DarkOakLeaves, CherryLeaves, MangroveLeaves, AzaleaLeaves, FloweringAzaleaLeaves,
    Ice, Snow, Snow2, PowderSnow,
    StoneSlab, OakSlab, StoneStairs, OakStairs,
    Torch, WallTorch, SoulTorch, SoulWallTorch, RedstoneTorch, RedstoneWallTorch,
    Fire, SoulFire,
    Grass, Fern, DeadBush, Dandelion, Poppy, BlueOrchid, Allium, AzureBluet,
    RedTulip, OrangeTulip, WhiteTulip, PinkTulip, OxeyeDaisy, Cornflower,
    LilyOfTheValley, WitherRose, BrownMushroom, RedMushroom,
    CrimsonFungus, WarpedFungus, CrimsonRoots, WarpedRoots, NetherSprouts,
    OakSapling, SpruceSapling, BirchSapling, JungleSapling, AcaciaSapling,
    DarkOakSapling, CherrySapling,
    Vine, WeepingVines, TwistingVines, GlowLichen, LilyPad,
    Seagrass, TallSeagrass, KelpPlant, Kelp,
    SporeBlossom, Azalea, FloweringAzalea, MossCarpet, HangingRoots,
    Ladder, SweetBerryBush, Cactus, SugarCane, Bamboo, SeaPickle,
    TubeCoral, BrainCoral, BubbleCoral, FireCoral, HornCoral,
    DeadTubeCoral, DeadBrainCoral, DeadBubbleCoral, DeadFireCoral, DeadHornCoral,
    TubeCoralFan, BrainCoralFan, BubbleCoralFan, FireCoralFan, HornCoralFan,
    DeadTubeCoralFan, DeadBrainCoralFan, DeadBubbleCoralFan, DeadFireCoralFan, DeadHornCoralFan,
);

const CROSSED_BITMASK: [u64; 7] = bitmask!(
    Grass, Fern, DeadBush,
    Dandelion, Poppy, BlueOrchid, Allium, AzureBluet,
    RedTulip, OrangeTulip, WhiteTulip, PinkTulip, OxeyeDaisy, Cornflower,
    LilyOfTheValley, WitherRose, BrownMushroom, RedMushroom,
    CrimsonFungus, WarpedFungus, CrimsonRoots, WarpedRoots, NetherSprouts,
    OakSapling, SpruceSapling, BirchSapling, JungleSapling, AcaciaSapling,
    DarkOakSapling, CherrySapling,
    SugarCane, Bamboo, LilyPad, Vine, WeepingVines, TwistingVines, GlowLichen,
    Ladder, SweetBerryBush,
    Torch, SoulTorch, RedstoneTorch,
    Fire, SoulFire,
);

impl BlockId {
    pub const fn name(&self) -> &'static str {
        match self {
            BlockId::Air => "Air",
            BlockId::Stone => "Stone",
            BlockId::GrassBlock => "Grass",
            BlockId::Dirt => "Dirt",
            BlockId::Cobblestone => "Cobble",
            BlockId::OakPlanks => "Planks",
            BlockId::Bedrock => "Bedrock",
            BlockId::Water => "Water",
            BlockId::Sand => "Sand",
            BlockId::Gravel => "Gravel",
            BlockId::GoldOre => "GoldOre",
            BlockId::IronOre => "IronOre",
            BlockId::CoalOre => "CoalOre",
            BlockId::OakLog => "OakLog",
            BlockId::OakLeaves => "Leaves",
            BlockId::Glass => "Glass",
            BlockId::CraftingTable => "C.Table",
            BlockId::Furnace => "Furnace",
            BlockId::Chest => "Chest",
            BlockId::Torch => "Torch",
            BlockId::Bricks => "Bricks",
            BlockId::StoneBricks => "StBrick",
            BlockId::SnowBlock => "Snow",
            BlockId::GoldBlock => "Gold",
            BlockId::IronBlock => "Iron",
            BlockId::DiamondBlock => "Diamond",
            BlockId::LapisBlock => "Lapis",
            BlockId::Bookshelf => "Books",
            BlockId::Netherrack => "Nether",
            BlockId::Obsidian => "Obsid",
            BlockId::Sponge => "Sponge",
            BlockId::HayBlock => "Hay",
            BlockId::Melon => "Melon",
            BlockId::Pumpkin => "Pumpkin",
            BlockId::Deepslate => "Deepslate",
            BlockId::Granite => "Granite",
            BlockId::Diorite => "Diorite",
            BlockId::Andesite => "Andesite",
            BlockId::Sandstone => "Sandstone",
            BlockId::Snow => "Snow",
            BlockId::Ice => "Ice",
            BlockId::Lava => "Lava",
            BlockId::Grass => "TallGrass",
            BlockId::Fern => "Fern",
            BlockId::DeadBush => "DeadBush",
            BlockId::Dandelion => "Dandelion",
            BlockId::Poppy => "Poppy",
            BlockId::BlueOrchid => "BlueOrchid",
            BlockId::OxeyeDaisy => "OxeyeDaisy",
            BlockId::Cornflower => "Cornflower",
            BlockId::RedTulip => "RedTulip",
            BlockId::BrownMushroom => "B.Mushroom",
            BlockId::RedMushroom => "R.Mushroom",
            BlockId::Cactus => "Cactus",
            BlockId::SugarCane => "SugarCane",
            BlockId::Vine => "Vine",
            BlockId::LilyPad => "LilyPad",
            BlockId::OakSapling => "Sapling",
            BlockId::SpruceSapling => "SpruceSap",
            BlockId::BirchSapling => "BirchSap",
            BlockId::JungleSapling => "JungleSap",
            BlockId::AcaciaSapling => "AcaciaSap",
            BlockId::DarkOakSapling => "DarkOakSap",
            BlockId::SpruceLog => "SpruceLog",
            BlockId::BirchLog => "BirchLog",
            BlockId::JungleLog => "JungleLog",
            BlockId::AcaciaLog => "AcaciaLog",
            BlockId::DarkOakLog => "DarkOakLog",
            BlockId::SpruceLeaves => "SpruceLvs",
            BlockId::BirchLeaves => "BirchLvs",
            BlockId::JungleLeaves => "JungleLvs",
            BlockId::AcaciaLeaves => "AcaciaLvs",
            BlockId::DarkOakLeaves => "DarkOakLvs",
            BlockId::SprucePlanks => "SprcPlank",
            BlockId::BirchPlanks => "BrchPlank",
            BlockId::JunglePlanks => "JnglPlank",
            BlockId::AcaciaPlanks => "AcacPlank",
            BlockId::DarkOakPlanks => "DrkPlank",
            BlockId::MossyCobblestone => "MossCobble",
            BlockId::CobbledDeepslate => "CblDeepsl",
            BlockId::PolishedDeepslate => "PolDeepsl",
            BlockId::DeepslateBricks => "DpBricks",
            BlockId::DeepslateTiles => "DpTiles",
            BlockId::DeepslateCoalOre => "DpCoal",
            BlockId::DeepslateIronOre => "DpIron",
            BlockId::DeepslateGoldOre => "DpGold",
            BlockId::DeepslateDiamondOre => "DpDiamond",
            BlockId::DeepslateRedstoneOre => "DpRedstn",
            BlockId::DeepslateLapisOre => "DpLapis",
            BlockId::DeepslateEmeraldOre => "DpEmerald",
            BlockId::DiamondOre => "DiamondOre",
            BlockId::RedstoneOre => "RedstnOre",
            BlockId::LapisOre => "LapisOre",
            BlockId::EmeraldOre => "EmeraldOre",
            BlockId::CopperOre => "CopperOre",
            BlockId::CopperBlock => "Copper",
            BlockId::RawIronBlock => "RawIron",
            BlockId::RawGoldBlock => "RawGold",
            BlockId::RawCopperBlock => "RawCopper",
            BlockId::AmethystBlock => "Amethyst",
            BlockId::Tuff => "Tuff",
            BlockId::Calcite => "Calcite",
            BlockId::DripstoneBlock => "Dripstone",
            BlockId::Glowstone => "Glowstone",
            BlockId::SeaLantern => "SeaLantern",
            BlockId::Shroomlight => "Shroomlight",
            BlockId::JackOLantern => "JackOLant",
            BlockId::CarvedPumpkin => "CrvdPumpk",
            BlockId::RedstoneLamp => "RstnLamp",
            BlockId::SoulSand => "SoulSand",
            BlockId::SoulSoil => "SoulSoil",
            BlockId::RedSand => "RedSand",
            BlockId::Prismarine => "Prismarin",
            BlockId::PrismarineBricks => "PrismBrik",
            BlockId::DarkPrismarine => "DkPrism",
            BlockId::Spawner => "Spawner",
            BlockId::MushroomStem => "MshrmStem",
            BlockId::RedMushroomBlock => "RedMshCap",
            BlockId::BrownMushroomBlock => "BrnMshCap",
            BlockId::StoneSlab => "StnSlab",
            BlockId::OakSlab => "OakSlab",
            BlockId::StoneStairs => "StnStair",
            BlockId::OakStairs => "OakStair",
            BlockId::WhiteCarpet => "WhtCarpet",
            BlockId::RedCarpet => "RedCarpet",
            BlockId::RedWool => "RedWool",
            BlockId::WhiteWool => "WhiteWool",
            BlockId::MagmaBlock => "Magma",
            BlockId::Ladder => "Ladder",
            BlockId::Bamboo => "Bamboo",
            BlockId::SweetBerryBush => "BerryBush",
            BlockId::CryingObsidian => "CryObsid",
            BlockId::BoneBlock => "BoneBlock",
            BlockId::NetherBricks => "NetherBri",
            BlockId::RedNetherBricks => "RedNethrB",
            BlockId::EndStone => "EndStone",
            BlockId::PurpurBlock => "Purpur",
            BlockId::MossBlock => "Moss",
            BlockId::Podzol => "Podzol",
            BlockId::CoarseDirt => "CrsDirt",
            BlockId::Mycelium => "Mycelium",
            BlockId::Mud => "Mud",
            BlockId::PackedMud => "PckdMud",
            BlockId::MudBricks => "MudBricks",
            BlockId::MangroveRoots => "MngrRoots",
            BlockId::MuddyMangroveRoots => "MdyRoots",
            BlockId::Terracotta => "Terracotta",
            BlockId::WhiteTerracotta => "WhtTerrac",
            BlockId::Blackstone => "Blackston",
            BlockId::PolishedBlackstone => "PolBlack",
            BlockId::PolishedBlackstoneBricks => "PolBlkBri",
            BlockId::CrimsonNylium => "CrimNylium",
            BlockId::WarpedNylium => "WarpNylium",
            BlockId::Basalt => "Basalt",
            BlockId::PolishedBasalt => "PolBasalt",
            BlockId::SmoothStone => "SmthStone",
            BlockId::SmoothSandstone => "SmthSand",
            BlockId::SmoothQuartz => "SmthQuart",
            BlockId::QuartzBlock => "Quartz",
            BlockId::ChiseledQuartzBlock => "ChslQuart",
            BlockId::QuartzPillar => "QrtzPilar",
            // Colored wools
            BlockId::OrangeWool => "OrngWool",
            BlockId::MagentaWool => "MagWool",
            BlockId::LightBlueWool => "LBluWool",
            BlockId::YellowWool => "YlwWool",
            BlockId::LimeWool => "LimeWool",
            BlockId::PinkWool => "PinkWool",
            BlockId::GrayWool => "GrayWool",
            BlockId::LightGrayWool => "LGryWool",
            BlockId::CyanWool => "CyanWool",
            BlockId::PurpleWool => "PrplWool",
            BlockId::BlueWool => "BlueWool",
            BlockId::BrownWool => "BrwnWool",
            BlockId::GreenWool => "GrnWool",
            BlockId::BlackWool => "BlckWool",
            // Colored terracottas
            BlockId::OrangeTerracotta => "OrngTerr",
            BlockId::MagentaTerracotta => "MagTerra",
            BlockId::LightBlueTerracotta => "LBluTerr",
            BlockId::YellowTerracotta => "YlwTerra",
            BlockId::LimeTerracotta => "LimeTerr",
            BlockId::PinkTerracotta => "PinkTerr",
            BlockId::GrayTerracotta => "GrayTerr",
            BlockId::LightGrayTerracotta => "LGryTerr",
            BlockId::CyanTerracotta => "CyanTerr",
            BlockId::PurpleTerracotta => "PrplTerr",
            BlockId::BlueTerracotta => "BlueTerr",
            BlockId::BrownTerracotta => "BrwnTerr",
            BlockId::GreenTerracotta => "GrnTerr",
            BlockId::RedTerracotta => "RedTerra",
            BlockId::BlackTerracotta => "BlckTerr",
            // Concrete
            BlockId::WhiteConcrete => "WhtConc",
            BlockId::OrangeConcrete => "OrngConc",
            BlockId::MagentaConcrete => "MagConc",
            BlockId::LightBlueConcrete => "LBluConc",
            BlockId::YellowConcrete => "YlwConc",
            BlockId::LimeConcrete => "LimeConc",
            BlockId::PinkConcrete => "PinkConc",
            BlockId::GrayConcrete => "GrayConc",
            BlockId::LightGrayConcrete => "LGryConc",
            BlockId::CyanConcrete => "CyanConc",
            BlockId::PurpleConcrete => "PrplConc",
            BlockId::BlueConcrete => "BlueConc",
            BlockId::BrownConcrete => "BrwnConc",
            BlockId::GreenConcrete => "GrnConc",
            BlockId::RedConcrete => "RedConc",
            BlockId::BlackConcrete => "BlckConc",
            // Concrete powder
            BlockId::WhiteConcretePowder => "WhtCPwd",
            BlockId::OrangeConcretePowder => "OrngCPwd",
            BlockId::MagentaConcretePowder => "MagCPwd",
            BlockId::LightBlueConcretePowder => "LBluCPwd",
            BlockId::YellowConcretePowder => "YlwCPwd",
            BlockId::LimeConcretePowder => "LimeCPwd",
            BlockId::PinkConcretePowder => "PinkCPwd",
            BlockId::GrayConcretePowder => "GrayCPwd",
            BlockId::LightGrayConcretePowder => "LGryCPwd",
            BlockId::CyanConcretePowder => "CyanCPwd",
            BlockId::PurpleConcretePowder => "PrplCPwd",
            BlockId::BlueConcretePowder => "BlueCPwd",
            BlockId::BrownConcretePowder => "BrwnCPwd",
            BlockId::GreenConcretePowder => "GrnCPwd",
            BlockId::RedConcretePowder => "RedCPwd",
            BlockId::BlackConcretePowder => "BlckCPwd",
            // Stained glass
            BlockId::WhiteStainedGlass => "WhtSGlass",
            BlockId::OrangeStainedGlass => "OrngSGls",
            BlockId::MagentaStainedGlass => "MagSGlas",
            BlockId::LightBlueStainedGlass => "LBluSGls",
            BlockId::YellowStainedGlass => "YlwSGlas",
            BlockId::LimeStainedGlass => "LimeSGls",
            BlockId::PinkStainedGlass => "PinkSGls",
            BlockId::GrayStainedGlass => "GraySGls",
            BlockId::LightGrayStainedGlass => "LGrySGls",
            BlockId::CyanStainedGlass => "CyanSGls",
            BlockId::PurpleStainedGlass => "PrplSGls",
            BlockId::BlueStainedGlass => "BlueSGls",
            BlockId::BrownStainedGlass => "BrwnSGls",
            BlockId::GreenStainedGlass => "GrnSGls",
            BlockId::RedStainedGlass => "RedSGlas",
            BlockId::BlackStainedGlass => "BlckSGls",
            BlockId::TintedGlass => "TntdGlas",
            // Shulker boxes
            BlockId::ShulkerBox => "Shulker",
            BlockId::WhiteShulkerBox => "WhtShul",
            BlockId::OrangeShulkerBox => "OrngShul",
            BlockId::MagentaShulkerBox => "MagShul",
            BlockId::LightBlueShulkerBox => "LBluShul",
            BlockId::YellowShulkerBox => "YlwShul",
            BlockId::LimeShulkerBox => "LimeShul",
            BlockId::PinkShulkerBox => "PinkShul",
            BlockId::GrayShulkerBox => "GrayShul",
            BlockId::LightGrayShulkerBox => "LGryShul",
            BlockId::CyanShulkerBox => "CyanShul",
            BlockId::PurpleShulkerBox => "PrplShul",
            BlockId::BlueShulkerBox => "BlueShul",
            BlockId::BrownShulkerBox => "BrwnShul",
            BlockId::GreenShulkerBox => "GrnShul",
            BlockId::RedShulkerBox => "RedShul",
            BlockId::BlackShulkerBox => "BlckShul",
            // Carpet
            BlockId::OrangeCarpet => "OrngCrpt",
            BlockId::MagentaCarpet => "MagCrpt",
            BlockId::LightBlueCarpet => "LBluCrpt",
            BlockId::YellowCarpet => "YlwCrpt",
            BlockId::LimeCarpet => "LimeCrpt",
            BlockId::PinkCarpet => "PinkCrpt",
            BlockId::GrayCarpet => "GrayCrpt",
            BlockId::LightGrayCarpet => "LGryCrpt",
            BlockId::CyanCarpet => "CyanCrpt",
            BlockId::PurpleCarpet => "PrplCrpt",
            BlockId::BlueCarpet => "BlueCrpt",
            BlockId::BrownCarpet => "BrwnCrpt",
            BlockId::GreenCarpet => "GrnCrpt",
            BlockId::BlackCarpet => "BlckCrpt",
            // Coral blocks
            BlockId::TubeCoralBlock => "TubeCrl",
            BlockId::BrainCoralBlock => "BrainCrl",
            BlockId::BubbleCoralBlock => "BublCrl",
            BlockId::FireCoralBlock => "FireCrl",
            BlockId::HornCoralBlock => "HornCrl",
            BlockId::DeadTubeCoralBlock => "DTubeCrl",
            BlockId::DeadBrainCoralBlock => "DBrainCrl",
            BlockId::DeadBubbleCoralBlock => "DBublCrl",
            BlockId::DeadFireCoralBlock => "DFireCrl",
            BlockId::DeadHornCoralBlock => "DHornCrl",
            // Coral
            BlockId::TubeCoral => "TubeCor",
            BlockId::BrainCoral => "BrainCor",
            BlockId::BubbleCoral => "BublCor",
            BlockId::FireCoral => "FireCor",
            BlockId::HornCoral => "HornCor",
            BlockId::DeadTubeCoral => "DTubeCor",
            BlockId::DeadBrainCoral => "DBrainCor",
            BlockId::DeadBubbleCoral => "DBublCor",
            BlockId::DeadFireCoral => "DFireCor",
            BlockId::DeadHornCoral => "DHornCor",
            // Coral fans
            BlockId::TubeCoralFan => "TubeFan",
            BlockId::BrainCoralFan => "BrainFan",
            BlockId::BubbleCoralFan => "BublFan",
            BlockId::FireCoralFan => "FireFan",
            BlockId::HornCoralFan => "HornFan",
            BlockId::DeadTubeCoralFan => "DTubeFan",
            BlockId::DeadBrainCoralFan => "DBrainFan",
            BlockId::DeadBubbleCoralFan => "DBublFan",
            BlockId::DeadFireCoralFan => "DFireFan",
            BlockId::DeadHornCoralFan => "DHornFan",
            // Wood/log variants
            BlockId::OakLog2 => "OakLog",
            BlockId::CherryLog => "CheryLog",
            BlockId::MangroveLog => "MangLog",
            BlockId::StrippedOakLog => "StrpOak",
            BlockId::StrippedSpruceLog => "StrpSprc",
            BlockId::StrippedBirchLog => "StrpBirc",
            BlockId::StrippedJungleLog => "StrpJngl",
            BlockId::StrippedAcaciaLog => "StrpAcac",
            BlockId::StrippedDarkOakLog => "StrpDrkO",
            BlockId::StrippedCherryLog => "StrpCher",
            BlockId::StrippedMangroveLog => "StrpMang",
            BlockId::OakWood => "OakWood",
            BlockId::SpruceWood => "SprcWood",
            BlockId::BirchWood => "BircWood",
            BlockId::JungleWood => "JnglWood",
            BlockId::AcaciaWood => "AcacWood",
            BlockId::DarkOakWood => "DrkOWood",
            BlockId::CherryWood => "CherWood",
            BlockId::MangroveWood => "MangWood",
            BlockId::StrippedOakWood => "SOakWd",
            BlockId::StrippedSpruceWood => "SSprcWd",
            BlockId::StrippedBirchWood => "SBircWd",
            BlockId::StrippedJungleWood => "SJnglWd",
            BlockId::StrippedAcaciaWood => "SAcacWd",
            BlockId::StrippedDarkOakWood => "SDrkOWd",
            BlockId::StrippedCherryWood => "SCherWd",
            BlockId::StrippedMangroveWood => "SMangWd",
            BlockId::OakPlanks2 => "Planks",
            BlockId::CherryPlanks => "CherPlk",
            BlockId::MangrovePlanks => "MangPlk",
            BlockId::BambooPlanks => "BambPlk",
            BlockId::BambooMosaic => "BambMosa",
            BlockId::OakLeaves2 => "Leaves",
            BlockId::CherryLeaves => "CherLvs",
            BlockId::MangroveLeaves => "MangLvs",
            BlockId::AzaleaLeaves => "AzaLvs",
            BlockId::FloweringAzaleaLeaves => "FlwAzaLv",
            // Plants & flowers
            BlockId::Allium => "Allium",
            BlockId::AzureBluet => "AzBluet",
            BlockId::OrangeTulip => "OrngTulp",
            BlockId::WhiteTulip => "WhtTulip",
            BlockId::PinkTulip => "PinkTulp",
            BlockId::LilyOfTheValley => "LilyVal",
            BlockId::WitherRose => "WithRose",
            BlockId::CrimsonFungus => "CrmFung",
            BlockId::WarpedFungus => "WrpFung",
            BlockId::CrimsonRoots => "CrmRoots",
            BlockId::WarpedRoots => "WrpRoots",
            BlockId::NetherSprouts => "NthrSprt",
            BlockId::WeepingVines => "WeepVine",
            BlockId::TwistingVines => "TwstVine",
            BlockId::GlowLichen => "GlwLichn",
            BlockId::Seagrass => "SeaGrass",
            BlockId::TallSeagrass => "TallSGrs",
            BlockId::Kelp => "Kelp",
            BlockId::KelpPlant => "KelpPlnt",
            BlockId::DriedKelpBlock => "DryKelpB",
            BlockId::SporeBlossom => "SporeBls",
            BlockId::Azalea => "Azalea",
            BlockId::FloweringAzalea => "FlwAzal",
            BlockId::MossCarpet => "MossCrpt",
            BlockId::HangingRoots => "HangRoot",
            BlockId::RootedDirt => "RootDirt",
            BlockId::SeaPickle => "SeaPickl",
            // Ice variants
            BlockId::BlueIce => "BlueIce",
            BlockId::PackedIce => "PckIce",
            BlockId::FrostedIce => "FrstIce",
            BlockId::Snow2 => "Snow",
            BlockId::PowderSnow => "PwdrSnow",
            // Saplings
            BlockId::CherrySapling => "CherySap",
            // Copper variants
            BlockId::ExposedCopper => "ExpCopper",
            BlockId::WeatheredCopper => "WthCopper",
            BlockId::OxidizedCopper => "OxdCopper",
            BlockId::CutCopper => "CutCopper",
            BlockId::ExposedCutCopper => "ExpCutCu",
            BlockId::WeatheredCutCopper => "WthCutCu",
            BlockId::OxidizedCutCopper => "OxdCutCu",
            BlockId::WaxedCopperBlock => "WaxCBlk",
            BlockId::WaxedExposedCopper => "WaxExpCu",
            BlockId::WaxedWeatheredCopper => "WaxWthCu",
            BlockId::WaxedOxidizedCopper => "WaxOxdCu",
            BlockId::WaxedCutCopper => "WaxCutCu",
            BlockId::WaxedExposedCutCopper => "WExCutCu",
            BlockId::WaxedWeatheredCutCopper => "WWthCutCu",
            BlockId::WaxedOxidizedCutCopper => "WOxdCutCu",
            // Deepslate
            BlockId::DeepslateCopperOre => "DpCopper",
            // Special blocks
            BlockId::WallTorch => "WTorch",
            BlockId::Fire => "Fire",
            BlockId::SoulFire => "SoulFire",
            BlockId::SoulTorch => "SoulTrch",
            BlockId::SoulWallTorch => "SWallTrc",
            BlockId::RedstoneTorch => "RstnTrch",
            BlockId::RedstoneWallTorch => "RWstnTrc",
            BlockId::EndRod => "EndRod",
            BlockId::RespawnAnchor => "RspwnAnc",
            BlockId::Target => "Target",
            BlockId::Lodestone => "Loadston",
            BlockId::HoneyBlock => "HoneyBlk",
            BlockId::HoneycombBlock => "HonycmBl",
            BlockId::NetherGoldOre => "NthrGOre",
            BlockId::AncientDebris => "AncDebri",
            BlockId::NetheriteBlock => "NthertBl",
            BlockId::AmethystCluster => "AmethCls",
            BlockId::BuddingAmethyst => "BudAmeth",
            BlockId::QuartzStairs => "QrtzStrs",
            BlockId::EmeraldBlock => "Emerald",
            BlockId::RedstoneBlock => "Redstone",
            BlockId::WetSponge => "WetSponge",
            BlockId::SmoothRedSandstone => "SmthRdSd",
            BlockId::PurpurPillar => "PrprPillr",
            BlockId::EndStoneBricks => "EndStBri",
            BlockId::OakDoor => "OakDoor",
            BlockId::OakFence => "OakFence",
            BlockId::RedstoneDust => "RedstDust",
        }
    }

    pub fn from_repr(value: u16) -> Option<Self> {
        // BlockId discriminants are contiguous; keep this bound in sync.
        // Use a match for O(1) lookup via the compiler's jump table.
        // When adding new variants, update MAX_DISCRIMINANT to match.
        const MAX_DISCRIMINANT: u16 = 413;
        if value > MAX_DISCRIMINANT {
            return None;
        }
        // SAFETY: every u16 in 0..=MAX_DISCRIMINANT maps to a valid BlockId variant.
        Some(unsafe { std::mem::transmute(value) })
    }

    pub fn from_name(s: &str) -> Option<Self> {
        let lower = s.to_lowercase();
        match lower.as_str() {
            "air" => Some(BlockId::Air),
            "stone" => Some(BlockId::Stone),
            "grass" | "grass_block" => Some(BlockId::GrassBlock),
            "dirt" => Some(BlockId::Dirt),
            "cobblestone" | "cobble" => Some(BlockId::Cobblestone),
            "oak_planks" | "planks" => Some(BlockId::OakPlanks),
            "bedrock" => Some(BlockId::Bedrock),
            "water" => Some(BlockId::Water),
            "sand" => Some(BlockId::Sand),
            "gravel" => Some(BlockId::Gravel),
            "gold_ore" => Some(BlockId::GoldOre),
            "iron_ore" => Some(BlockId::IronOre),
            "coal_ore" => Some(BlockId::CoalOre),
            "oak_log" => Some(BlockId::OakLog),
            "oak_leaves" | "leaves" => Some(BlockId::OakLeaves),
            "glass" => Some(BlockId::Glass),
            "crafting_table" => Some(BlockId::CraftingTable),
            "furnace" => Some(BlockId::Furnace),
            "chest" => Some(BlockId::Chest),
            "torch" => Some(BlockId::Torch),
            "bricks" => Some(BlockId::Bricks),
            "stone_bricks" | "stonebricks" => Some(BlockId::StoneBricks),
            "snow_block" | "snow" => Some(BlockId::SnowBlock),
            "gold_block" => Some(BlockId::GoldBlock),
            "iron_block" => Some(BlockId::IronBlock),
            "diamond_block" => Some(BlockId::DiamondBlock),
            "lapis_block" => Some(BlockId::LapisBlock),
            "bookshelf" => Some(BlockId::Bookshelf),
            "netherrack" => Some(BlockId::Netherrack),
            "obsidian" => Some(BlockId::Obsidian),
            "sponge" => Some(BlockId::Sponge),
            "hay_block" => Some(BlockId::HayBlock),
            "melon" => Some(BlockId::Melon),
            "pumpkin" => Some(BlockId::Pumpkin),
            "deepslate" => Some(BlockId::Deepslate),
            "granite" => Some(BlockId::Granite),
            "diorite" => Some(BlockId::Diorite),
            "andesite" => Some(BlockId::Andesite),
            "sandstone" => Some(BlockId::Sandstone),
            "lava" => Some(BlockId::Lava),
            "cactus" => Some(BlockId::Cactus),
            "sugar_cane" | "sugarcane" => Some(BlockId::SugarCane),
            "vine" | "vines" => Some(BlockId::Vine),
            "lily_pad" => Some(BlockId::LilyPad),
            "mossy_cobblestone" => Some(BlockId::MossyCobblestone),
            "cobbled_deepslate" => Some(BlockId::CobbledDeepslate),
            "glowstone" => Some(BlockId::Glowstone),
            "sea_lantern" => Some(BlockId::SeaLantern),
            "shroomlight" => Some(BlockId::Shroomlight),
            "jack_o_lantern" => Some(BlockId::JackOLantern),
            "redstone_lamp" => Some(BlockId::RedstoneLamp),
            "oak_door" => Some(BlockId::OakDoor),
            "oak_fence" => Some(BlockId::OakFence),
            "redstone_dust" | "redstone_wire" => Some(BlockId::RedstoneDust),
            "soul_sand" => Some(BlockId::SoulSand),
            "soul_soil" => Some(BlockId::SoulSoil),
            "red_sand" => Some(BlockId::RedSand),
            "prismarine" => Some(BlockId::Prismarine),
            "spawner" => Some(BlockId::Spawner),
            "nether_bricks" => Some(BlockId::NetherBricks),
            "end_stone" => Some(BlockId::EndStone),
            "moss_block" => Some(BlockId::MossBlock),
            "podzol" => Some(BlockId::Podzol),
            "coarse_dirt" => Some(BlockId::CoarseDirt),
            "mycelium" => Some(BlockId::Mycelium),
            "mud" => Some(BlockId::Mud),
            "terracotta" => Some(BlockId::Terracotta),
            "blackstone" => Some(BlockId::Blackstone),
            "basalt" => Some(BlockId::Basalt),
            "smooth_stone" => Some(BlockId::SmoothStone),
            "quartz_block" => Some(BlockId::QuartzBlock),
            "magma_block" | "magma" => Some(BlockId::MagmaBlock),
            "sweet_berry_bush" | "berry_bush" => Some(BlockId::SweetBerryBush),
            "ladder" => Some(BlockId::Ladder),
            "bamboo" => Some(BlockId::Bamboo),
            "bone_block" => Some(BlockId::BoneBlock),
            "purpur_block" => Some(BlockId::PurpurBlock),
            _ => None,
        }
    }

    pub fn is_solid(&self) -> bool {
        let d = *self as u16;
        (NON_SOLID_BITMASK[(d / 64) as usize] >> (d % 64)) & 1 == 0
    }

    pub fn is_crossed(&self) -> bool {
        let d = *self as u16;
        (CROSSED_BITMASK[(d / 64) as usize] >> (d % 64)) & 1 == 1
    }

    pub fn is_transparent(&self) -> bool {
        let d = *self as u16;
        (TRANSPARENT_BITMASK[(d / 64) as usize] >> (d % 64)) & 1 == 1
    }

    pub fn is_climbable(&self) -> bool {
        matches!(
            self,
            BlockId::Vine | BlockId::WeepingVines | BlockId::TwistingVines | BlockId::Ladder
        )
    }

    pub fn is_slab(&self) -> bool {
        matches!(self, BlockId::StoneSlab | BlockId::OakSlab)
    }

    pub fn is_stair(&self) -> bool {
        matches!(self, BlockId::StoneStairs | BlockId::OakStairs)
    }

    #[allow(dead_code)]
    pub fn light_level(&self) -> u8 {
        match self {
            BlockId::Torch | BlockId::WallTorch => 14,
            BlockId::EndRod => 14,
            BlockId::Glowstone | BlockId::Shroomlight | BlockId::SeaLantern => 15,
            BlockId::Fire => 15,
            BlockId::SoulFire => 10,
            BlockId::SoulTorch | BlockId::SoulWallTorch => 10,
            BlockId::RedstoneTorch | BlockId::RedstoneWallTorch => 7,
            BlockId::JackOLantern => 15,
            BlockId::Lava => 15,
            BlockId::RedstoneLamp => 15,
            BlockId::Furnace => 13,
            BlockId::MagmaBlock => 3,
            BlockId::AmethystCluster => 5,
            BlockId::GlowLichen => 7,
            _ => 0,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum BlockFace {
    Top,
    Bottom,
    Left,
    Right,
    Front,
    Back,
}

pub const FACES: [BlockFace; 6] = [
    BlockFace::Top,
    BlockFace::Bottom,
    BlockFace::Left,
    BlockFace::Right,
    BlockFace::Front,
    BlockFace::Back,
];

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Block {
    pub id: BlockId,
    /// Compact registry-local state ordinal. `data` remains the compatibility
    /// representation for the legacy fluid/slab/stair paths while they migrate.
    pub state: u16,
    pub data: u8,
}

impl Block {
    pub const fn new(id: BlockId) -> Self {
        Block {
            id,
            state: 0,
            data: 0,
        }
    }

    pub fn with_legacy_data(id: BlockId, data: u8) -> Self {
        let state = match id {
            BlockId::Water | BlockId::Lava => crate::world::block_registry::registry()
                .state_for_properties(id, [("level", if data > 15 { "15" } else { match data {
                    0 => "0", 1 => "1", 2 => "2", 3 => "3", 4 => "4", 5 => "5", 6 => "6", 7 => "7",
                    8 => "8", 9 => "9", 10 => "10", 11 => "11", 12 => "12", 13 => "13", 14 => "14", _ => "15",
                }}), ("falling", "false")])
                .unwrap_or(0),
            BlockId::StoneSlab | BlockId::OakSlab => {
                let slab_type = if data == 1 { "top" } else { "bottom" };
                crate::world::block_registry::registry()
                    .state_for_properties(id, [("type", slab_type)])
                    .unwrap_or(0)
            }
            BlockId::StoneStairs | BlockId::OakStairs => {
                let facing = ["south", "west", "north", "east"][(data & 0x03) as usize];
                let half = if data & 0x04 == 0 { "bottom" } else { "top" };
                crate::world::block_registry::registry()
                    .state_for_properties(id, [("facing", facing), ("half", half), ("shape", "straight")])
                    .unwrap_or(0)
            }
            _ => 0,
        };
        Block { id, state, data }
    }

    pub fn with_properties<'a>(
        id: BlockId,
        properties: impl IntoIterator<Item = (&'a str, &'a str)>,
    ) -> Option<Self> {
        let state = crate::world::block_registry::registry().state_for_properties(id, properties)?;
        Some(Block { id, state, data: 0 })
    }

    pub const fn air() -> Self {
        Block {
            id: BlockId::Air,
            state: 0,
            data: 0,
        }
    }

    pub fn is_air(&self) -> bool {
        matches!(self.id, BlockId::Air)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compact_state_round_trips_registry_properties() {
        let block = Block::with_properties(BlockId::StoneStairs, [("facing", "west"), ("half", "top"), ("shape", "straight")])
            .expect("supported stair properties must resolve");
        let properties = crate::world::block_registry::registry()
            .properties_for_state(BlockId::StoneStairs, block.state)
            .expect("resolved state must decode");
        assert_eq!(properties, vec![("facing", "west"), ("half", "top"), ("shape", "straight")]);
    }

    #[test]
    fn invalid_block_discriminant_is_rejected() {
        assert_eq!(BlockId::from_repr(414), None);
        assert_eq!(BlockId::from_repr(BlockId::Torch as u16), Some(BlockId::Torch));
    }

    #[test]
    fn legacy_stair_data_migrates_to_registry_state() {
        let block = Block::with_legacy_data(BlockId::StoneStairs, 0b110);
        let properties = crate::world::block_registry::registry()
            .properties_for_state(block.id, block.state)
            .unwrap();
        assert_eq!(properties, vec![("facing", "north"), ("half", "top"), ("shape", "straight")]);
    }
}
